# Generated by Django 5.0.4 on 2024-05-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.TextField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('Category', models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milk Shake')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
