# Generated by Django 5.0.3 on 2024-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milk Shake'), ('BT', 'Belts'), ('WT', 'Watches')], max_length=2),
        ),
    ]
